client:
  discovery: http://localhost:9999/ip/list

ipConfig:
  addr: 0.0.0.0:9999/ip/list
  etcdService: im/gatewayServer/
  endPoints:
    - http://localhost:2379
    - http://localhost:2380
    - http://localhost:2381
  dailTimeOut: 5
  leaseDDL: 5


gateway:
  maxConnsNum: 1000000
  workPoolNum: 1023
  deviceId: 1
  addr: 0.0.0.0:4025
  endPoints:
    - http://localhost:2379
    - http://localhost:2380
    - http://localhost:2381
  epoll:
    maxTriggerEvent: 1024 # 最多一次触发的事件
  reactorNum: 3 #反应堆数
  dailTimeOut: 5
  leaseDDL: 5