client:
  login: http://localhost:9999/user/login
  maxReSendCount: 100

ipConfig:
  addr: 0.0.0.0:9999/user/login
  etcdService: im/gatewayServer/
  endPoints:
    - http://localhost:2379
    - http://localhost:2380
    - http://localhost:2381
  dailTimeOut: 5
  leaseDDL: 5


gateway:
  maxConnsNum: 1000000
  workPoolNum: 1023
  deviceId: 1
  addr: 0.0.0.0:4025
  authAddr: 0.0.0.0:9998
  endPoints:
    - http://localhost:2379
    - http://localhost:2380
    - http://localhost:2381
  epoll:
    maxTriggerEvent: 1024 # 最多一次触发的事件
  reactorNum: 3 #反应堆数
  dailTimeOut: 5
  leaseDDL: 5
  heartBeatTimeout: 3
  mq:
    xName: imSys.direct.msgRouter   # 交换机名字
    # queueNamePrefix, 与该gateway绑定的消息队列的前缀
    # 完整的gateway 名称需要拼接deviceId
    # 该队列用来接收下游转发过来的消息，此gateway是这个queue的唯一消费者
    queueNamePrefix: imSys.gateway.queue.
    routingKey: imSys.messaging.queue



mysql:
  db: mysql
  dbHost: 101.42.38.110
  dbPort: 3306
  dbUser: root
  dbPassWord: 2g0t0l374yyds
  dbName: im_system

redis:
  addr: 101.42.38.110:6379
  password: 2g0t0l374yyds
  db: 0

mq:
  user: user
  password: user
  ip: localhost
  host: 5672
  xName: direct.msgRouter
  upMessage:
    xName: imSys.direct.msgRouter
    privateMsg:
      queueName: private.queue
      bindingKey: msg.private
    groupMsg:
      queueName: group.queue
      bindingKey: msg.group



messaging:
  mqConsumerNum: 8 #cpu核心数决定,消费消息的协程数量
  mq:
    xName: imSys.direct.msgRouter
    queueName: imSys.messaging.queue
    routingKeyPrefix: imSys.gateway.queue.
